# Generated by Django 3.1.3 on 2020-11-18 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreAlbum', models.CharField(max_length=50)),
                ('imagenAlbum', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreArtista', models.CharField(max_length=50)),
                ('descripcionArtista', models.TextField()),
                ('imagenArtista', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Estilo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEstilo', models.CharField(max_length=50)),
                ('imagenEstilo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCancion', models.CharField(max_length=50)),
                ('videoCancion', models.CharField(max_length=300)),
                ('albumCancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='top100.album')),
                ('artistaCancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='top100.artista')),
                ('estiloCancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='top100.estilo')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artistaAlbum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='top100.artista'),
        ),
        migrations.AddField(
            model_name='album',
            name='estiloAlbum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='top100.estilo'),
        ),
    ]
