# Generated by Django 3.1.3 on 2020-11-19 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('top100', '0002_album_descripcionalbum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='descripcionAlbum',
        ),
    ]
