# Generated by Django 3.1.3 on 2020-11-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top100', '0004_album_descripcionalbum'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='numeroAlbum',
            field=models.IntegerField(default=0),
        ),
    ]
