# Generated by Django 3.1.3 on 2020-11-22 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('top100', '0005_cancion_numeroalbum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancion',
            old_name='numeroAlbum',
            new_name='numeroRanking',
        ),
    ]
