# Generated by Django 3.1.3 on 2020-11-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top100', '0006_auto_20201122_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='estilo',
            name='descripcionEstilo',
            field=models.TextField(null=True),
        ),
    ]
